const dicionarioSimbolos = {
    'Precipício':'O risco e a fé. O limite entre o conhecido e o desconhecido, não temer a vastidão, visão privilegiada.',
    'Trouxa':'Carregar apenas o essencial, experiências passadas',
    'Cachorro':'É o instinto de animal domesticado, fidelidade, proteção, conexão com a natureza intuitiva.',
    'Montanha':'Planos superiores, iluminação, realização espiritual, isolamento meditativo e pensamento puro. Desafios superados, ambição, estabilidade e objetivos elevados.',
    'Pena Vermelha':'Energia Vital, paixão e força de vontade. O impulso que nos leva a agir.',
    'Leminiscata':'O ciclo eterno de renovação e a energia que flui continuamente',
    'Árvore da Vida': 'O caminho espiritual da ascensão e a descida da luz divina. A manifestação da energia divina na matéria e a estrutura da abundância.',
    'Ouroboros':'Renovação eterna, sabedoria, a autossuficiencia, o entendimento de que o fim é apenas um novo começo.',
    'Pergaminho':'A Lei Maior e o conhecimento oculto. Sabedoria acessada pelo estudo profundo. A necessidade de estrutura, métodos claros e visão de longo prazo.',
    'Romãs':'Fertilidade, gestação e desejos.',
    'Véu':'A proteção do inconsciente, aquilo que está escondido atrás das aparências, a compaixão e a espiritualidade. Um lugar que só acessado por quem está pronto para ver a verdade.',
    'Globo':'Diversidade de possibilidades, desejo de expansão',
    'Armadura':'Prontidão para o combate, proteção e autoridade, estar sempre preparado para defender seu território.',
    'Montanhas Áridas':'Ambição e resiliência, a natureza indomável, a dureza necessária para manter o poder. O distanciamento emocional e a objetividade.',
    'Cabelos e Barba Brancos':'Sabedoria, ancestralidade e experiência acumulada. A autoridade que vem do tempo e das lições aprendidas. Idade avançada, maturidade, tempo dedicado ao estudo e à reflexão.',
    'Cabelos ao Vento':'A liberdade de pensamento e a vivacidade intelectual.',
    'Cabeça de Carneiro':'Liderança, iniciativa, determinação ou teimosia.',
    'Cabeça de Touro':'O elemento Terra, o signo de Touro a estabilidade, a força física, a resistência e o trabalho prático.',
    'Cabeça de Águia':'O elemento Água, o signo de Escorpião, a visão espiritual elevada e a renovação emocional.',
    'Lebre':'a fertilidade extrema, a agilidade dos sentidos e a reprodução rápida de ideias e bens.',
    'Sino':'Um aviso de chegada que remete à rejeição e ao isolamento.',
    'Igreja':'Lugar de proteção, necessidade de silêncio. Ter algo como sagrado, ter um projeto que transcende o próprio indivíduo',
    'Chaves':'As chaves do reino dos céus, o conceito de Doutrina e Vida, o acesso ao conhecimento que estava trancado, desbloqueio.',
    'Monges':'O conhecimento espiritual e a devoção. A transmissão do conhecimento, a relação entre mestre e aluno, estudo, mentoria, a importância de fazer parte de uma comunidade.',
    'Colunas':'Estabilidade e ordem institucional. A dualidade e o equilíbrio dos opostos.',
    'Sol':'A iluminação, a clareza mental e a energia vital.',
    'Casal':'A Integração. Os opostos e a dualidade. A polaridade entre harmonia e conflito. Pode ser intrepretado como Adão e Eva. A continuidade da vida, a união de forças e a construção de parcerias sólidas.',
    'Homem':'O consciente. O Logos, é a energia projetada para o mundo exterior. A capacidade de moldar a realidade, a lógica, a autoridade e a estrutura.',
    'Montanha':'Estabilidade, coisas duradouras, desafios, metas de longo prazo, a necessidade de esforço, a busca por uma perspectiva espiritual, isolamento, estruturas imutáveis.',
    'Nudez':'A verdade absoluta, a transparência, a inocência e a ausência de máscaras.',
    'Serpente':'A descida do espírito na matéria, o desejo e a busca pelo conhecimento.',
    'Cocheiro':'O ego vitorioso, a autoconfiança e a maestria sobre o plano material.',
    'Rio':'O fluxo das emoções e a necessidade de permanecer em movimento para não ser submerso por elas. Possui menor profundidade e vastidão que o Mar, exige uma necessidade menor de orientação mas ainda apresenta risco de afogamento, além de ter espaço para as criaturas desconhecidas do inconsciente.',
    'Lingam-Yoni':'A união das energias masculina e feminina. As asas acima apontam para a inspiração espiritual.',
    'Espada':'Consagração, honra e nobreza. O intelecto e a mente consciente como ferramentas de criação ou destruição. Execução de um pensamento.',
    'Balança':'Imparcialidade, a equidade, o julgamento e o equilíbrio.',
    'Bandeira Cristã':'A vitória do espírito sobre a morte e o despertar da consciência.',
    'Lamparina':'A luz da inteligência e a busca pela verdade. Diferente do Sol, é uma luz contida que ilumina apenas o próximo passo.',
    'Cajado':'O apoio na jornada e a vontade direcionada. É a ferramenta do peregrino que se sustenta na própria fé.',
    'Roda':'O ciclo eterno de nascimento, morte e renascimento; o movimento constante do destino e do tempo.',
    'Esfinge':'O equilíbrio e a estabilidade em meio à mudança. A lei espiritual que governa o destino, as dualidades',
    'Símbolos Alquímicos':'Os componentes básicos da vida e da transformação.',
    'Mulher':'O Inconsciente. A Anima, a intuição e a profundidade do mundo interior. Passividade no sentido de ser receptiva e criativa.',
    'Leão':'Coragem, os impulsos instintivos, a raiva, a libido e as paixões cruas. É a nossa natureza animal que precisa de integração, não de repressão.',
    'Árvore':'Abrigo e sombra, a necessidade de aterramento e proteção, a renovação e o processo de crescimento, a ponte entre o divino e o terreno. A vitalidade da natureza, a base fértil e a clareza mental.',
    'Auréola':'Iluminação, insight e clareza mental. A compreensão profunda surge quando cessamos a luta externa e nos voltamos para a introspecção.',
    'Aurora':'Novos começos, a luz da consciência superando a escuridão, esperança e renovação divina. A transição entre o oculto e o revelado, a iluminação espiritual ou a clareza mental rompendo a dúvida e o medo.',
    'Ânfora':'Recipiente da energia vital, a capacidade de conter, dosar e distribuir nossas emoções com equilíbrio.',
    'Anjo':'O Eu Superior ou a superconsciência. É o guia que traz clareza espiritual e proteção.',
    'Asas':'A agilidade mental, a imaginação elevada, a capacidade de transitar entre o mundo real e o espiritual, o poder de transcender limitações materiais.',
    'Asas Vermelhas':'A paixão espiritualizada e a energia vital ativa que impulsiona a alma.',
    'Bode':'Os instintos primordiais, a fertilidade descontrolada e a sombra que precisa ser integrada.',
    'Uva':'A abundância, os prazeres sensoriais, a embriaguez ou o vício material.',
    'Caminho':'A jornada da vida e o futuro, a continuidade dos projetos e a distância a ser percorrida em direção à expansão da consciência.',
    'Chifres':'O poder animal, a força bruta.',
    'Correntes':'O aprisionamento psicológico, vícios, dependências e a ilusão de estar preso por forças externas.',
    'Lagarto':'A conexão com os instintos mais básicos e sua transformação em sabedoria e paciência.',
    'Criança':'O Potencial. A inocência, a pureza, a alegria genuína, o potencial ilimitado e o início de uma jornada.',
    'Diabo':'Personificação das sombras internas, medos, obsessões, o foco exclusivo no plano material.',
    'Estandarte Vermelho':'Vitalidade, vitória sobre a escuridão, a celebração da vida.',
    'Fita Vermelha':'O fio da vida, a paixão ou a conexão entre o espírito e a ação física.',
    'Gato Preto':'A intuição aguçada, o mistério, a independência e o domínio sobre os instintos.',
    'Guirlanda':'A vitória, a honra e o reconhecimento.',
    'Festão':'A celebração, a vitória, a conclusão bem-sucedida, a harmonia e o florescimento dos esforços.',
    'Lagosta':'Os primeiros impulsos da consciência emergindo do subconsciente, o enfrentar de medos antigos.',
    'Lobo':'O instinto selvagem, a parte da natureza humana que ainda não foi domesticada.',
    'Pedinte':'A vulnerabilidade humana, a perda temporária de status e a necessidade de uma postura humilde.',
    'Atadura':'Situações difíceis ou experiências negativas, limitação física, a necessidade de repouso ou de receber ajuda.',
    'Vitral Colorido':'A conexão com o espiritual, auxílio espiritual, a esperança e a luz.',
    'Raio':'Intervenção súbita ou divina. Quebra de paradigmas, a ficha que cai repentinamente e a destruição de falsas certezas.',
    'Torre':'As construções do ego, estruturas rígidas.',
    'Triângulo':'A tríade corpo, mente e espírito, receptivade.',
    'Trombeta':'O chamado para o despertar, aviso espiritual.',
    'Trono':'Poder, autoridade, base sólida e estabilidade.',
    'Túmulo':'O limite entre o mundo externo e o interno, o fim das preocupações, o passado, a estagnação ou o estado de morte em vida.',
    'Yods':'A consciência divina e a força vital que desce para nutrir o mundo físico. A semente do pensamento e a influência divina na manifestação mental.',
    'Taça':'O coração e a mente subconsciente como recipientes da energia vital e divina, dos sentimentos, da intuição, a receptividade da alma.',
    'Coração':'A sede das emoções, da vitalidade e do afeto.',
    'Asas de Morcego':'A natureza instintiva e o lado sombrio do subconsciente.',
    'Árvore do Conhecimento':'A sabedoria, a dualidade entre o bem e o mal e as escolhas morais. A descida da consciência pura para a experiência sensorial.',
    'Cabeça de Leão':'O elemento Fogo e o signo de Leão. A força vital, a paixão, a coragem e a criatividade. O domínio sobre os instintos e a manifestação da vontade divina através da ação inspirada e do entusiasmo.',
    'Cabeça Humana':'O elemento Ar e o signo de Aquário. A inteligência, o pensamento lógico, a ética e a capacidade de abstração. A evolução consciente da humanidade e a busca pelo conhecimento espiritual através da mente.',
    'Caduceu de Hermes':'A medicina e a cura.',
    'Casa':'A estabilidade, a segurança e o potencial para construir algo sólido.',
    'Castelo':'A recompensa e o destino final da jornada, poder e estabilidade no mundo material, patrimônio herdado ou construído, a autoridade e as estruturas sociais.',
    'Concha':'A peregrinação emocional e a busca pela beleza ou pelo idealismo, receptividade e fertilidade.',
    'Dragão':'Os medos subconscientes e as forças instintivas.',
    'Pessoa Coberta de Branco':'A busca por iluminação espiritual ou a necessidade de uma verdade revelada, divindades ou seres espirituais.',
    'Frutas':'A colheita, a fertilidade e a abundância.',
    'Ilha':'Obstáculos que precisam ser navegados com clareza.',
    'Mulher':'O conhecimento oculto e a intuição passiva. A natureza fértil, a abundância sensorial e a capacidade de nutrir e manifestar a vida na matéria. O domínio dos instintos através da suavidade e da inteligência emocional. A vitória do espírito sobre a matéria.',
    'Navio':'O comércio, as trocas, a jornada da vida, oportunidades em movimento, a habilidade de navegar e procurar orientação.',
    'Pedras':'Um caminho desafiador mas que leva à possibilidade de uma realidade melhor.',
    'Peixe':'Nos fala que inconsciente é vivo. Quando ele surge saltando é a possibilidade de perceber algo de forma inesperada. A intuição que salta para a consciência de forma surpreendente.',
    'Ponte ':'Transição e conexão.',
    'Querubim':'Sabedoria e proteção divina, guardiões dos portais, mediação entre o humano e o divino.',
    'Rio':'O fluxo constante da vida e do tempo, a fertilidade.',
    'Serpente':'O conhecimento instintivo, a sensualidade, o perigo de ser seduzido por ilusões.',
    'Tesouro':'A ambição por riqueza e o desejo de abundância material.',
    'Folhas de Oliveira':'A paz, a reconciliação, o fim de um conflito e a restauração da harmonia interna ou externa.',
    'Folhas de Palma':'A vitória da alma sobre a carne, a imortalidade, a justiça e a regência do feminino sagrado.',
    'Barqueiro':'Um guia, a vontade consciente que direciona a mente.',
    'Tenda':'O ambiente social, o coletivo.',
    'Borboleta':'Transformação, libertação, leveza, renovação espiritual.',
    'Jardim':'Fertilidade, o cultivo das ideias e o resultado do esforço aplicado na natureza. A alma que cultivou sua própria realidade e agora vive em harmonia com a abundância.',
    'Arco':'A passagem para um novo estado de ser, o limite entre o planejado e o que começa a se manifestar.',
    'Montanhas Nevadas':'Preservação do essencial e cristalização da consciência. Fala sobre uma mente fria, no sentido de lúcida e objetiva. O rigor do destino, a frieza das circunstâncias e o isolamento social.',
    'Malabarista':'A destreza, o esforço consciente, manter as coisas em movimento, adaptação constante e a agilidade diante das demandas.',
    'Artesão':'A habilidade técnica, o esforço dedicado e o orgulho pelo trabalho bem feito.',
    'Videira':'A fonte dos recursos, os frutos do trabalho, segurança financeira, fertilidade, abundância extrema. Status, dignidade, celebração e beleza, prazer sensorial.',
    'Caracol':'A paciência, o progresso lento, a constância, a consciência de que a verdadeira riqueza leva tempo.',
    'Folhas de Carvalho':'A força, a longevidade, a proteção, a autoridade espiritual e a resistência do espírito diante das adversidades.',
    'Salamandra':'O elemento Fogo de forma pura e madura, a regeneração e a natureza transformadora. Quando aparece mordendo a própria cauda, faz referência ao Ouroboros. Neste sentido, também apresenta conexão com o símbolo da Fênix.',
    'Pirâmides':'A imortalidade, a sabedoria ancestral e a base sólida do poder.',
    'Quatro Seres': 'O Anjo (Aquáio), a Águia (Escorpião), o Leão (Leão) e o Touro (Touro). Os quatro elementos e a estabilidade do mundo físico em meio ao caos.',
    'Cruz Solar':'O equilíbrio entre os opostos, as quatro direções, as quatro estações e a união do divino com o terreno.',
    'Espelho de Vênus':'A feminilidade, o amor, a fertilidade e a conexão com as forças criativas da natureza.',
    'Vara de Barqueiro':'Acessar o oculto, capacidade de se locomover emocionalemente.',
    'Escudo':'Proteção e preservação.',
    'Livro':'Segredos que ainda não foram revelados ou que exigem intuição para serem lidos, conhecimento superior.',
    'Bandeira Preta':'A ausência de luz e o fim de um ciclo.',
    'Cama':'Local de repouso e recuperação.',
    'Símbolos Astrológicos':'Conexão entre a jornada humana e os ciclho universais, o destino e as influências planetárias.',
    'Japamala':'A oração estruturada, a tradição religiosa e a conexão disciplinada com o divino através de rituais.',
    'Anel':'União, compromisso e a eternidade dos ciclos.',
    'Guarda':'Vigilância e prontidão para proteger.',
    'Colar':'Poder, conexão, status, sabedoria acumulada e refinamento emocional.',
    'Ponta de Lança Lírio':'A nobreza de espírito e a intenção pura que guia a ação.',
    'Cruz Celta':'A ponte entre mundos, a espiritualidade ancestral que organiza o caos material.',
    'Janela':'O auxílio espiritual e a esperança que pode estar sendo ignorada.',
    'Ferramenta Agrícola':'O trabalho árduo, a paciência do plantio e a espera necessária para a colheita dos frutos materiais.',
    'Ferramenta de Entalhe':'A maestria, o foco no detalhe e o aprimoramento contínuo das próprias habilidades técnicas.',
    'Lança':'A direção, a vontade, a ação, o impulso para atingir um objetivo e a capacidade de penetrar na verdade ou defender os próprios ideais. O mergulho nas profundezas da psique.',
    'Ondinas ':'Seres elementais que governam o Elemento Água. Soberania absolura sobre as emoções.'
};
const listaSimbolos = document.getElementById('simbolos');
Object.entries(dicionarioSimbolos)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .forEach(([chave, valor]) => {
        const itemLista = document.createElement('li');
        itemLista.innerHTML = `
            <span class="chave">${chave}:</span> 
            <span class="valor">${valor}</span>
        `;
        listaSimbolos.appendChild(itemLista);
    });