const dicionarioSimbolos = {
    'Precipício':'O risco e a fé. O limite entre o conhecido e o desconhecido.',
    'Trouxa':'Carregar apenas o essencial. Expeciências passadas',
    'Rosa Branca':'Pureza e Inocência. Ausência de malícia, medo ou julgamento',
    'Rosa Vermelha':'',
    'Cachorro':'É o instinto de animal domesticado, fidelidade e Proteção. Conexão com a natureza intuitiva.',
    'Sol Branco':'O otimismo do início de um novo ciclo. A luz do espírito e a consciência divina. Proteção superior.',
    'Montanhas Nevadas':'Planos superiores, desafios superados. O gelo fala sobre preservar o que é essencial, sobre a cristalização da consciência. Fala sobre uma mente fria, no sentido de lúcida e objetiva. O cume nevado simboliza a realização espiritual, o isolamento necessário para a iluminação e a altura alcançada pelo pensamento puro.',
    'Pena Vermelha':'Energia Vital, paixão e força de vontade. O impulso que nos leva a agir.',
    'Olhar para o Alto':'Desconexão com a matéria e foco no ideal. Sintonia com o Universo',
    'Olhar para o Horizonte':'Planejamento de longo prazo, visão de futuro, contemplação de possibilidades, expectativas e desapego do presente imediato.',
    'Braço Erguido':'Antena para o Domínio Espiritual e para o Domínio Mental. Canalizar inspiração e transformá-la em ação.',
    'Mão apontando para baixo':'Conexão com o que é terreno e material. Assim em cima como embaixo. A execução prática do que foi planejado.',
    'Leminiscata':'Domínio sobre os ciclos e a mente. Ausência de limitação nos pensamentos. A compreensãod e que a energia é eterna.',
    'Árvore da Vida': 'Representa o caminho espiritual da ascensão e a descida da luz divina.',
    'Os Quatro Naipes do Tarot':'Ter todas as ferramentas necessárias para vencer.',
    'Túnica Branca':'Pureza de espírito e de intenção, neutralidade. A base ética e a alma limpa por trás das intenções.',
    'Túnica Vermelha':'A força vital e o desejo de agir.',
    'Manto Vermelho':'Paixão, poder e experiência. O vermelho também representa o sangue e a vida.',
    'Ouroboros':'Renovação eterna, sabedoria, a autossuficiencia, o entendimento de que o fim é apenas um novo começo.',
    'Flores':'Aspirações e desejos realizados. O florescimento das ideias, sentimentos e projetos.',
    'Colunas do Templo de Salomão':'B e J:Boaz (Negra) e Jachin (Branca). A dualidade:luz/sombra, positivo/negativo, masculino/feminino. O equilíbrio dos opostos.',
    'Véu com romãs':'A proteção do inconsciente e a fertilidade oculta. O que está escondido atrás das aparências. Só entra quem está pronto para ver a verdade.',
    'Pergaminho':'A Lei Maior e o conhecimento oculto. Sabedoria que não é ensinada em escolas, mas acessada pela intuição e estudo profundo.',
    'Lua aos Pés':'Domínio sobre as emoções e o subconsciente. Conexão com os ciclos femininos, as marés emocionais e os sonhos.',
    'Cruz Solar':'O equilíbrio entre os quatro elementos. A união do espiritual com o material.',
    'Coroa de Ísis':'As fases da Lua, a conexão com a divindade feminina e o tempo que as coisas levam para maturar. ',
    'Manto Azul':'O elemento Água, fluidez emocional e a profundidade dos sentimentos que correm como um rio.',
    'Mar':'O reservatório imenso do inconsciente coletivo.',
    'Símbolo de Vênus':'O amor, a beleza e a harmonia. O poder feminino, a diplomacia e a valorização do que é belo e estético.',
    'Campo de Trigo':'Colheita, fertilidade e nutrição. Abundância material e o resultado concreto de algo que foi plantado e cuidado.',
    'Coroa de Doze Estrelas':'Domínio sobre o tempo (meses) e o zodíaco. Conexão com os ciclos naturais e a sabedoria cósmica aplicada ao dia a dia.',
    'Cetro com Orbe':'Poder de governar o mundo material. Liderança através do afeto e da criatividade, não pela força bruta.',
    'Romãs':'Fertilidade, gestação e desejos. A capacidade de dar luz a novos projetos, ideias ou até mesmo vida física.',
    'Trono de Pedra':'O poder que não se abala, a base sólida, autoridade.',
    'Cruz Ansata (ou Ankh)':'Símbolo egípcio da vida. O direito de governar e a responsabilidade sobre a vida dos súditos.',
    'Globo na Mão Esquerda':'Domínio sobre o mundo material. Ter o controle da situação "na palma da mão"; visão estratégica.',
    'Armadura':'Prontidão para o combate. Proteção e autoridade; estar sempre preparado para defender seu território.',
    'Montanhas Áridas':'Ambição e resiliência.	A natureza indomável, a dureza necessária para manter o poder. O distanciamento emocional, a objetividade e a solidez das conquistas.',
    'Cabelos e Barba Brancos':'Sabedoria e experiência.	A autoridade que vem do tempo e das lições aprendidas na prática. Símbolo clássico da idade, da experiência acumulada, da maturidade e do tempo dedicado ao estudo e à meditação.',
    'Cabeça de Carneiro':'Liderança, iniciativa, determinação e uma pitada de teimosia.',
    'Mitra':'Domínio sobre os três mundos (Físico, Mental e Espiritual).	Autoridade completa e sabedoria que abrange todas as áreas da vida.',
    'Cetro de Três Cruzes':'Cruzes	Poder sobre a Igreja e a tradição.	O respeito ao que já foi testado e aprovado pelo tempo; o poder da fé.',
    'Igreja':'O solo sagrado, o santuário de proteção e a necessidade de silêncio.',
    'Chaves Cruzadas':'As chaves do reino dos céus:Doutrina e Vida. O acesso ao conhecimento que estava trancado. É o "desbloqueio" de uma habilidade.',
    'Dois Discípulos':'A transmissão do conhecimento:Mestre e Aluno. Estudo, mentoria e a importância de fazer parte de uma comunidade.',
    'Mão de Papa':'Benção e ensino (dois dedos levantados, dois dobrados).	A ponte entre o que é visível e o que é invisível; a didática.',
    'Duas Colunas':'Estabilidade e ordem institucional. Diferente das colunas da Sacerdotisa (Mistério), estas são sólidas e estruturadas.',
    'Tapete Quadriculado':'O caminho da vida e a dualidade humana.	O chão onde pisamos; a prática cotidiana dentro de regras estabelecidas.',
    'Sol':'Simboliza a iluminação, a clareza mental e a energia vital que nutre a consciência.',
    'Casal':'Os opostos e a dualidade. Pode ser intrepretado com Adão e Eva. A figura masculina representa a mente consciente e o intelecto. A figura feminina representa a mente subconsciente. ',
    'Montanha':'Estabilidade, desafios, metas de longo prazo, a necessidade de esforço, de ter uma perspectiva espiritual, isolamento, estruturas imutáveis.',
    'Nudez':'Simboliza a verdade absoluta, a transparência, a inocência e a ausência de máscaras.',
    'Serpente':'Representa a descida do espírito na matéria, o desejo e a busca pelo conhecimento.',
    'Cocheiro':'Representa o ego vitorioso, a autoconfiança e a maestria sobre o plano material.',
    'Esfinges':'Simbolizam as dualidades:luz e sombra, positivo e negativo. Elas puxam em direções opostas, exigindo controle constante.',
    'Lua Crescente':'A intuição latente, os ciclos de mudança e a luz limitada que guia o pensamento.',
    'Cetro':'O poder para manifestar intenções e autoridade mágica.',
    'Cidade ao Fundo':'Simboliza a civilização e o conforto que o cocheiro deixou para trás em busca de uma meta maior.',
    'Rio':'Representa o fluxo das emoções e a necessidade de permanecer em movimento para não ser submerso por elas.',
    'Escudo':'O símbolo central (Lingam-Yoni) representa a união das energias masculina e feminina; as asas acima indicam inspiração espiritual.',
    'Espada em Riste':'A defesa da verdade, o discernimento, a autoridade, a prontidão para o julgamento e a retidão de caráter. A mente como ferramenta de criação ou destruição. É um símbolo fálico, representa a força ativa das ideias.',
    'Espada na Horizontal':'Impasse, paralisia mental, bloqueios autoimpostos.',
    'Espada':'Consagração, honra e nobreza. O intelecto e a mente consciente como ferramentas de criação ou destruição.',
    'Espada Fincada':'Os fardos mentais, as crenças limitantes e as experiências do passado. Algo que deve ser deixado ou que não pôde ser carregado. Ameaças e pressões externas.',
    'Balança':'Simboliza a imparcialidade, o equilíbrio entre forças opostas e a pesagem de evidências ou ações (causa e efeito).',
    'Trono entre Pilares':'Representa a estabilidade e a estrutura da lei. Os dois pilares evocam a dualidade e, portanto, necessidade de mediação.',
    'Pano de Fundo (Roxo)':'Simboliza a compaixão e a espiritualidade que devem temperar a severidade do julgamento.',
    'Expressão Serena':'Diferente de um juiz punitivo, a face é impassível, indicando que a justiça não é emocional, mas sim uma consequência natural dos fatos.',
    'Lamparina':'Representa a luz da inteligência e a busca pela verdade. Diferente do Sol, é uma luz contida que ilumina apenas o próximo passo.',
    'Estrela de Seis Pontas':'Selo de Salomão simboliza o equilíbrio entre o macrocosmo e o microcosmo, a união do espiritual e do material.',
    'Cajado':'O apoio na jornada e a vontade direcionada. É a ferramenta do peregrino que se sustenta na própria fé.',
    'Manto Cinza':'Representa a invisibilidade, a discrição e a proteção contra as distrações do mundo exterior; o cinza é a cor da neutralidade e da sabedoria.',
    'Olhar para Baixo':'Indica introspecção e a consciência de que a verdadeira jornada é interna. Ele olha para o caminho que já percorreu para guiar os que vêm atrás.',
    'Postura Curvada':'Humildade diante do vasto conhecimento do universo. O peso da sabedoria adquirida, da responsabilidade ou culpa que o indivíduo carrega sobre os ombros.',
    'Postura Inclinada':'Movimento, ação em progresso.',
    'Postura Deitada':'A rendição absoluta, o fim da resistência e a morte simbólica de uma ideia ou situação.',
    'Roda':'Representa o ciclo eterno de nascimento, morte e renascimento; o movimento constante do destino e do tempo.',
    'Esfinge':'Simboliza o equilíbrio e a estabilidade em meio à mudança. Ela detém a espada da justiça, representando a lei espiritual que governa o destino.',
    'Os Quatro Seres.':'O Anjo (Aquário), a Águia (Escorpião), o Leão (Leão) e o Touro (Touro). Representam os quatro elementos e a estabilidade do mundo físico em meio ao caos.',
    'Símbolos Alquímicos':'No círculo interno, aparecem símbolos para Mercúrio, Enxofre, Sal e Água, ou seja, os componentes básicos da vida e da transformação.',
    'Mulher':'Representa o Self conscisomnambulismente e a inteligência emocional. É a psique superior que atua através da paciência e da diplomacia, e não da força bruta.',
    'Leão':'Simboliza o Id, os impulsos instintivos, a raiva, a libido e as paixões cruas. É a nossa natureza animal que precisa de integração, não de repressão.',
    'Coroa de Flores':'Harmonia entre o humano e o divino, vitória espiritual, celebração da vida e a conexão com a natureza. Diferente da coroa de metal (que representa autoridade mundana/rígida), a coroa de flores sugere uma liderança ou vitória baseada na compaixão, intuição e inteligência emocional.',
    'Postura Invertida':'Representa a inversão de valores e a mudança de perspectiva. Na saúde mental, simboliza olhar para um problema de um ângulo completamente novo, rompendo padrões cognitivos habituais.',
    'Árvore':'Oferece abrigo e sombra, simbolizando a necessidade de aterramento e proteção, a renovação e o processo de crescimento a ponte entre o divino e o terreno.',
    'Auréola':'A luz ao redor da cabeça indica iluminação, insight e clareza mental. Sugere que a compreensão profunda surge quando cessamos a luta externa e nos voltamos para a introspecção.',
    'Aurora':'Novos começos, a luz da consciência superando a escuridão, esperança e renovação divina. A transição entre o oculto e o revelado, a iluminação espiritual ou a clareza mental rompendo a dúvida e o medo.',
    'Pernas Cruzadas':'A perna cruzada forma o número quatro, associado à estabilidade e ao mundo material. No Arcano O Pendurado, indica que o mundo físico está em suspensão, priorizando o trabalho interno sobre a ação externa.',
    'Braços formando um Triângulo':'Os braços dobrados atrás das costas formam um triângulo invertido, símbolo da água e do receptivo. Representa a submissão consciente e a abertura para receber sabedoria sem resistência.',
    'Cavalo Branco':'O cavalo branco simboliza a pureza do movimento e a força vital que conduz a transformação. Sua cor indica que a mudança, embora difícil, é um processo de limpeza e clareza.',
    'Água':'Representa o subconsciente, as emoções e o fluxo da intuição. É o elemento da cura e da limpeza emocional.',
    'Ânfora':'Recipiente da energia vital; simboliza a capacidade de conter, dosar e distribuir nossas emoções com equilíbrio.',
    'Anjo':'Representa o "Eu Superior" ou a superconsciência. É o guia que traz clareza espiritual e proteção.',
    'Asas':'A agilidade mental, a imaginação elevada, a capacidade de transitar entre o mundo real e o espiritual, o poder de transcender limitações materiais.',
    'Asas Vermelhas':'Representam a paixão espiritualizada e a energia vital ativa que impulsiona a alma.',
    'Bastões':'Representam a vontade, a criatividade, o impulso vital e a autoridade mágica.',
    'Bode':'Representa os instintos primordiais, a fertilidade descontrolada e a sombra que precisa ser integrada.',
    'Uva':'Simboliza a abundância, os prazeres sensoriais e, em excesso, a embriaguez ou o vício material.',
    'Cálice':'Representa o elemento Água:receptáculo dos sentimentos, do amor, da intuição e da receptividade da alma.',
    'Caminho':'A jornada da vida; representa o processo de evolução e a distância a ser percorrida até a iluminação.',
    'Chifres':'Simbolizam o poder animal, a força bruta.',
    'Bastões (Dois)':'Simbolizam o domínio total sobre as polaridades, positiva e negativa e a manifestação completa',
    'Coroa':'A autoridade, a conquista e o controle do ego. A vitória da mente sobre a matéria e o sucesso por meio do propósito.',
    'Correntes':'Simbolizam o aprisionamento psicológico, vícios, dependências e a ilusão de estar preso por forças externas.',
    'Criança':'A inocência, a pureza, a alegria genuína, e o início de uma jornada.',
    'Diabo':'Personificação das sombras internas, medos, obsessões e o foco exclusivo no plano material.',
    'Estandarte Vermelho':'Símbolo de vitalidade vibrante e da vitória solar sobre a escuridão; a celebração da vida.',
    'Estrela':'Guia de esperança e renovação; representa a luz interna que brilha após os momentos de crise.',
    'Fita Vermelha':'Representa o "fio" da vida, a paixão ou a conexão entre o espírito e a ação física.',
    'Flores (Íris)':'Mensageiras de harmonia e paz; simbolizam a moderação e a comunicação entre o céu e a terra.',
    'Fogo':'Energia de transformação, destruição necessária e faísca divina da inspiração e do desejo.',
    'Girassol':'A alma voltada para a luz; representa felicidade, vitalidade, crescimento e o sucesso absoluto.',
    'Guirlanda de Louros':'Símbolo de conclusão bem-sucedida, triunfo, proteção e o ciclo eterno da vida que se fecha.',
    'Lago':'O reservatório do inconsciente; águas paradas que guardam mistérios, sonhos e medos profundos.',
    'Lagosta':'Representa os primeiros impulsos da consciência emergindo do subconsciente; o enfrentar de medos arcaicos.',
    'Lobo':'O instinto selvagem e o medo do desconhecido; a parte da natureza humana que ainda não foi domesticada.',
    'Lua':'O reino das ilusões, dos sonhos e da intuição; reflete a luz solar de forma indireta e misteriosa.',
    'Nuvens Cincentas':'Confusão mental, turbulência emocional, o véu que encobre a verdade temporariamente.',
    'Nuvens Rajadas':'A tempestade que passou, deixando um rastro de tensão. Dinamismo, clareza cortante.',
    'Vitral Colorido':'A conexão com o espiritual, a esperança e a luz.',
    'Pássaro':'Agilidade, liberdade, comunicação rápida, pensamento elevado, conexão espiritual, a natureza volátil da mente. Quando em bando: A multiplicidade de ideias.',
    'Pentagrama Invertido':'Simboliza a matéria dominando o espírito; a inversão dos valores éticos e o foco no ego.',
    'Raio':'Intervenção súbita, quebra de paradigmas, "insight" violento e a destruição de falsas certezas.',
    'Reflexo':'A dualidade entre o que é real e o que é percebido; a projeção das nossas sombras no mundo exterior.',
    'Torre':'As construções do ego; estruturas rígidas que precisam cair para permitir o crescimento da alma.',
    'Triângulo':'Representa a tríade (corpo, mente e espírito); o fogo da aspiração espiritual.',
    'Trombeta':'O chamado para o despertar; o som que ativa a consciência e convoca para a renovação.',
    'Trono':'Estabilidade e autoridade. O lugar onde a consciência se assenta para governar a vida.',
    'Túmulo':'O limite entre o mundo externo e o interno. O fim das preocupações. O passado, a estagnação ou o estado de morte em vida.',
    'Yods':'A consciência divina e a força vital que desce para nutrir o mundo físico. A semente do pensamento e a influência divina na manifestação mental.',
    'Taça':'O coração e a mente subconsciente como receptáculos da energia vital e divina.',
    'Coração':'A sede das emoções, da vitalidade e do afeto.',
    'Chuva':'A liberação emocional, a tristeza purificadora e a limpeza necessária da alma.',
    'Águas Calmas':'A serenidade, o espelho da alma em harmonia.',
    'Banco':'A base sólida da mente e das emoções que sustentam seu estado emocional. A estabilidade rígida, a imobilidade, um lugar para a reflexão.',
    'Braços Cruzados':'O fechamento para o mundo externo, a defensiva e a concentração na vida interior.',
    'Cabeça de Leão Alada':'A paixão elevada à espiritualidade, a energia instintiva transformada em propósito.',
    'Cabeça Humana':'Representa o desejo de status, inteligência ou a busca por uma identidade social idealizada.',
    'Caduceu de Hermes':'A medicina e a cura.',
    'Casa':'A estabilidade, a segurança e o potencial para construir algo sólido.',
    'Castelo':'Segurança, o lar e o destino final da jornada. Poder e estabilidade no mundo material. A autoridade e as estruturas sociais.',
    'Céu Límpido':'Clareza mental, transparência, desapego, neutralidade. Ausência de agendas ocultas, de tensões, de conflitos, de dúvidas. O campo aberto para o raciocínio.',
    'Chapéu com Lenço':'A mente que se permite flutuar em devaneios e imaginação.',
    'Chapéu Vermelho':'Uma mente movida pelo entusiasmo e pelo desejo. A pureza das intenções e a vivacidade das memórias afetivas.',
    'Concha':'A peregrinação emocional e a busca pela beleza ou pelo idealismo. Receptividade e fertilidade.',
    'Coroa de Louros':'O desejo de vitória, reconhecimento e sucesso.',
    'Dragão':'Os medos subconscientes e as forças instintivas.',
    'Elmo com Crista':'A mente inspirada e a conexão com planos superiores de pensamento.',
    'Figura Coberta de Branco':'A busca por iluminação espiritual ou a necessidade de uma verdade revelada.',
    'Flor de Lótus':'Pureza espiritual, emoções elevadas, renovação e a manifestação da consciência acima do subconsciente.',
    'Lírios':'A pureza e a intenção clara.',
    'Frutas':'A colheita, a fertilidade e a abundância.',
    'Grama Verde':'Potencial de crescimento, terreno fértil.',
    'Lua com Rosto':'A intuição guiando o caminho durante a noite escura da alma. Indica que a jornada é interna e emocional.',
    'Manto Branco':'A pureza e a honestidade consigo mesmo.',
    'Manto Preto':'O luto, a tristeza, o peso das emoções negativas, forças trevosas e obsessores.',
    'Mão Saindo da Nuvem':'Uma oferta ou oportunidade que surge do plano espiritual, um presente da consciência superior. Uma ideia ou insight que surge do plano espiritual.',
    'Mar Agitado':'Instabilidade interna, conflito emocional. Forças profundas e não controladas que estão vindo à tona.',
    'Mar Calmo':'A serenidade de entender as próprias marés internas. O subconsciente em repouso. A paz de espírito e a estabilidade. Estagnação emocional, apatia.',
    'Ilhas':'Obstáculos que precisam ser navegados com clareza.',
    'Margens Áridas':'O contraste entre a água e a terra seca sugere a capacidade de trazer vida e fertilidade para onde antes só havia deserto.',
    'Mulher':'O conhecimento oculto e a intuição passiva. A natureza fértil, a abundância sensorial e a capacidade de nutrir e manifestar a vida na matéria. O domínio dos instintos através da suavidade e da inteligência emocional. A vitória do espírito sobre a matéria.',
    'Navio':'O comércio, a jornada da vida e a habilidade de navegar em situações complexas com segurança e direção clara.',
    'Nuvens':'Desejos e pensamentos que ainda não foram aterrados, ideias voláteis e instáveis.',
    'Olhar Calmo e Direto':'Uma mente que não se deixa levar por impulsos.',
    'Olhar Fixo':'A introspecção e a capacidade de ler as entrelinhas. Enxergar o que está oculto aos olhos comuns.',
    'Olhar Para Baixo':'A busca interna e a recusa em se distrair com o que é superficial. Olhar o que é negativo dentro de si e de seu passado e se apegar a isso, se recusando a se abrir para o presente e para o futuro.',
    'Pátio de Pedra':'Uma estrutura sólida, as memórias formam a base sobre a qual construímos nossa identidade.',
    'Pedras':'O caminho à frente será desafiador e exigirá esforço, mas leva à possibilidade de uma consciência mais elevada.',
    'Peixe':'Indica que o inconsciente é vivo.',
    'Peixe Saltando':'Um insight inesperado. O peixe simboliza a intuição que salta para a consciência de forma surpreendente.',
    'Pomba Branca':'A paz, a descida do espírito na matéria e a nutrição espiritual do ser.',
    'Ponte ':'Transição e conexão.',
    'Postura Sentada':'A estabilidade, a autossuficiência, a satisfaçãoa, a confiança e o conforto',
    'Querubim':'Sabedoria e proteção divina, guardiões dos portais, mediação entre o humano e o divino.',
    'Rio':'O fluxo constante das emoções e do tempo. As águas de um rio não param, sugerindo que as emoções, sejam elas boas ou ruins, passarão. Também indica fertilidade.',
    'Serpente':'O conhecimento instintivo, a sensualidade, o perigo de ser seduzido por ilusões.',
    'Taça Fechada':'Os segredos do subconsciente, pensamentos profundos e reservados.',
    'Taças Derrubadas':'Decepções, projetos que falharam ou relacionamentos que chegaram ao fim. O líquido derramado é aquilo que não pode ser recuperado.',
    'Taças em Pé':'Esperança, lições aprendidas e conexões sólidas.',
    'Taças no Chão':'Experiências passadas ou ofertas atuais que já não trazem satisfação ou que são ignoradas no momento.',
    'Taças Empilhadas':'A estrutura de vida que foi construída até o momento presente.',
    'Tesouro':'A ambição por riqueza e o desejo de abundância material.',
    'Olhos Vendados':'A busca pela visão interior e o isolamento dos sentidos. A negação da realidade externa, a falta de clareza, a ignorância sobre a própria situação.',
    'Ramos de Oliveira e Palma':'A dualidade entre paz/reconciliação e vitória/triunfo, frequentemente associados à maestria sobre o intelecto e emoções.',
    'Barqueiro':'Um guia, a vontade consciente que direciona a mente.',
    'Olhar para Trás':'A vigilância, o medo de ser descoberto ou o apego ao que ficou no passado.',
    'Tenda':'O ambiente social, o coletivo.',
    'Terreno Enlameado':'A instabilidade emocional, a dificuldade de caminhar e o peso do subconsciente.',
    'Mãos Cobrindo o Rosto':'A vergonha, o desespero e a recusa em encarar a realidade ou a dor.',
    'Espada Inclinada':'Dinamismo, conflito ou transição.',
    'Cabelo ao Vento':'A liberdade de pensamento e a vivacidade intelectual.',
    'Cavalo a Galope':'Movimento e velocidade, ação impulsiva, foco no objetivo.',
    'Borboleta':'Transformação, libertação, leveza, renovação espiritual.',
    'Postura Frontal':'Consciência plena, estabilidade, poder consolidado e ações diretas. Manifestação de forma física e imediata, assumindo controle total, sem ocultar suas intenções ou olhar para o passado ou para o futuro.',
    'Estrela de Oito Pontas':'PESQUISAR',
    '':'',
    '':'',
    '':'',
    '':'',
    '':''

};
const listaSimbolos = document.getElementById('simbolos');
Object.entries(dicionarioSimbolos)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .forEach(([chave, valor]) => {
        const itemLista = document.createElement('li');
        itemLista.innerHTML = `
            <span class="chave">${chave}:</span> 
            <span class="valor">${valor}</span>
        `;
        listaSimbolos.appendChild(itemLista);
    });