const dicionarioSimbolos = {
    'Precipício': 'O risco e a fé. O limite entre o conhecido e o desconhecido.',
    'Trouxa': 'Carregar apenas o essencial. Expeciências passadas',
    'Rosa Branca': 'Pureza e Inocência. Ausência de malícia, medo ou julgamento',
    'Cachorro': 'É o instinto de animal domesticado, fidelidade e Proteção. Conexão com a natureza intuitiva.',
    'Sol Branco': 'O otimismo do início de um novo ciclo. A luz do espírito e a consciência divina. Proteção superior.',
    'Montanhas Nevadas': 'Planos superiores, desafios superados. O gelo fala sobre preservar o que é essencial, sobre a cristalização da consciência. Fala sobre uma mente fria, no sentido de lúcida e objetiva. O cume nevado simboliza a realização espiritual, o isolamento necessário para a iluminação e a altura alcançada pelo pensamento puro.',
    'Pena Vermelha': 'Energia Vital, paixão e força de vontade. O impulso que nos leva a agir.',
    'Olhar para o Alto': 'Desconexão com a matéria e foco no ideal. Sintonia com o Universo',
    'Braço Erguido': 'Antena para o Domínio Espiritual e para o Domínio Mental. Canalizar inspiração e transformá-la em ação.',
    'Mão apontando para baixo': 'Conexão com o que éterreno e material. Assim em cima como embaixo. A execução prática do que foi planejado.',
    'Leminiscata': 'Domínio sobre os ciclos e a mente. Ausência de limitação nos pensamentos. A compreensãod e que a energia é eterna.',
    'Os Quatro Naipes do Tarot': 'Ter todas as ferramentas necessárias para vencer.',
    'Túnica Branca': 'Pureza de Espírito. A base ética e a alma limpa por trás das intenções. Na saúde mental, remete à clareza de consciência necessária para enfrentar as próprias sombras.',
    'Manto Vermelho': 'Paixão, poder e experiência. O vermelho também representa o sangue, a vida.',
    'Ouroboros': 'Renovação eterna, sabedoria, a autossuficiencia, o entendimento de que o fim é apenas um novo começo.',
    'Flores': 'Aspirações e desejos realizados. O florescimento das ideias.',
    'Colunas do Templo de Salomão': 'B e J: Boaz (Negra) e Jachin (Branca). A dualidade: luz/sombra, positivo/negativo, masculino/feminino. O equilíbrio dos opostos.',
    'Véu com romãs': 'A proteção do inconsciente e a fertilidade oculta. O que está escondido atrás das aparências. Só entra quem está pronto para ver a verdade.',
    'Pergaminho': 'A Lei Maior e o conhecimento oculto. Sabedoria que não é ensinada em escolas, mas acessada pela intuição e estudo profundo.',
    'Lua aos Pés': 'Domínio sobre as emoções e o subconsciente. Conexão com os ciclos femininos, as marés emocionais e os sonhos.',
    'Cruz Solar': 'O equilíbrio entre os quatro elementos. A união do espiritual com o material.',
    'Coroa de Ísis': 'As fases da Lua, a conexão com a divindade feminina e o tempo que as coisas levam para maturar. ',
    'Manto Azul': 'O elemento Água, fluidez emocional e a profundidade dos sentimentos que correm como um rio.',
    'Mar': 'O reservatório imenso do inconsciente coletivo.',
    'Símbolo de Vênus': 'O amor, a beleza e a harmonia. O poder feminino, a diplomacia e a valorização do que é belo e estético.',
    'Campo de Trigo': 'Colheita, fertilidade e nutrição. Abundância material e o resultado concreto de algo que foi plantado e cuidado.',
    'Coroa de Doze Estrelas': 'Domínio sobre o tempo (meses) e o zodíaco. Conexão com os ciclos naturais e a sabedoria cósmica aplicada ao dia a dia.',
    'Cetro com Orbe': 'Poder de governar o mundo material. Liderança através do afeto e da criatividade, não pela força bruta.',
    'Romãs': 'Fertilidade, gestação e desejos. A capacidade de dar luz a novos projetos, ideias ou até mesmo vida física.',
    'Trono de Pedra': 'O poder que não se abala; a base sólida de um projeto ou instituição.' ,
    'Cruz Ansata (ou Ankh)': 'Símbolo egípcio da vida. O direito de governar e a responsabilidade sobre a vida dos súditos.',
    'Globo na Mão Esquerda': 'Domínio sobre o mundo material. Ter o controle da situação "na palma da mão"; visão estratégica.',
    'Armadura': 'Prontidão para o combate. Proteção e autoridade; estar sempre preparado para defender seu território.',
    'Montanhas Áridas': 'Ambição e resiliência.	A natureza indomável que ele conquistou; a dureza necessária para manter o poder.',
    'Cabelos e Barba Brancos': 'Sabedoria e experiência.	A autoridade que vem do tempo e das lições aprendidas na prática. Símbolo clássico da idade, da experiência acumulada, da maturidade e do tempo dedicado ao estudo e à meditação.',
    'Cabeça de Carneiro': 'Liderança, iniciativa, determinação e uma pitada de teimosia.',
    'Mitra': 'Domínio sobre os três mundos (Físico, Mental e Espiritual).	Autoridade completa e sabedoria que abrange todas as áreas da vida.',
    'Cetro de Três Cruzes': 'Cruzes	Poder sobre a Igreja e a tradição.	O respeito ao que já foi testado e aprovado pelo tempo; o poder da fé.',
    'Chaves Cruzadas': 'As chaves do reino dos céus (Doutrina e Vida).	O acesso ao conhecimento que estava trancado. É o "desbloqueio" de uma habilidade.',
    'Dois Discípulos': 'A transmissão do conhecimento (Mestre e Aluno).	Estudo, mentoria e a importância de fazer parte de uma comunidade ou grupo.',
    'Mão de Papa': 'Benção e ensino (dois dedos levantados, dois dobrados).	A ponte entre o que é visível e o que é invisível; a didática.',
    'Duas Colunas': 'Estabilidade e ordem institucional. Diferente das colunas da Sacerdotisa (Mistério), estas são sólidas e estruturadas.',
    'Tapete Quadriculado': 'O caminho da vida e a dualidade humana.	O chão onde pisamos; a prática cotidiana dentro de regras estabelecidas.',
    'Sol': 'Simboliza a iluminação, a clareza mental e a energia vital que nutre a consciência.',
    'Casal': 'Pode ser intrepretado com Adão e Eva. A figura masculina representa a mente consciente e o intelecto, ele olha para a mulher. A figura feminina representa a mente subconsciente, a intuição e o sentimento; ela olha para o anjo. ',
    'Árvore da Vida': 'Representa o caminho espiritual da ascensão e a descida da luz divina.',
    'Árvore do Conhecimento':'Simboliza a tentação e a experiência sensorial.',
    'Montanha': 'O pico central simboliza o caminho da ascensão, os desafios futuros e a meta espiritual. Simboliza a meta da individuação e os desafios transcendidos. Representa a estabilidade e a perspectiva de longo prazo no desenvolvimento pessoal.',
    'Nudez':'Simboliza a verdade absoluta, a transparência, a inocência e a ausência de máscaras.',
    'Serpente':'Representa a descida do espírito na matéria, o desejo e a busca pelo conhecimento.',
    'Cocheiro':'Representa o ego vitorioso, a autoconfiança e a maestria sobre o plano material.',
    'Esfinges':'Simbolizam as dualidades: luz e sombra, positivo e negativo. Elas puxam em direções opostas, exigindo controle constante.',
    'Ausência de Rédeas':'Indica que o controle é mental e espiritual (vontade), não baseado na força física.',
    'Dossel Estrelado':'O teto azul com estrelas representa a influência das forças celestiais e a proteção divina sobre a jornada.',
    'Lua Crescente no Ombro':'Chamadas de "Urim e Thummim", representam as emoções e a intuição que o cocheiro deve equilibrar.',
    'Cetro':'Simboliza a autoridade mágica e o poder de vontade para manifestar intenções.',
    'Cidade ao Fundo':'Simboliza a civilização e o conforto que o cocheiro deixou para trás em busca de uma meta maior.',
    'Rio':'Representa o fluxo das emoções e a necessidade de permanecer em movimento para não ser submerso por elas.',
    'Pomo Dourado':'Ação imediata, conquista merecida e a realização de um desejo importante, incentiva a ser rápido e perspicaz.',
    'Escudo':'O símbolo central (Lingam-Yoni) representa a união das energias masculina e feminina; as asas acima indicam inspiração espiritual.',
    'Espada em Riste':'Representa o discernimento e a capacidade de separar a verdade da mentira. Ela aponta para cima, indicando vitória e autoridade espiritual.',
    'Balança':'Simboliza a imparcialidade, o equilíbrio entre forças opostas e a pesagem de evidências ou ações (causa e efeito).',
    'Trono entre Pilares':'Representa a estabilidade e a estrutura da lei. Os dois pilares evocam a dualidade e, portanto, necessidade de mediação.',
    'Pano de Fundo (Roxo)':'Simboliza a compaixão e a espiritualidade que devem temperar a severidade do julgamento.',
    'Expressão Serena':'Diferente de um juiz punitivo, a face é impassível, indicando que a justiça não é emocional, mas sim uma consequência natural dos fatos.',
    'Lamparina':'Representa a luz da inteligência e a busca pela verdade. Diferente do Sol, é uma luz contida que ilumina apenas o próximo passo.',
    'Estrela de Seis Pontas':'Selo de Salomão simboliza o equilíbrio entre o macrocosmo e o microcosmo, a união do espiritual e do material.',
    'Cajado':'Simboliza o apoio na jornada espiritual, a autoridade conquistada pela experiência e a "árvore da vida" que sustenta o buscador.',
    'Manto Cinza':'Representa a invisibilidade, a discrição e a proteção contra as distrações do mundo exterior; o cinza é a cor da neutralidade e da sabedoria.',
    'Olhar para Baixo':'Indica introspecção e a consciência de que a verdadeira jornada é interna. Ele olha para o caminho que já percorreu para guiar os que vêm atrás.',
    'Postura Curvada':'Sugere humildade diante do vasto conhecimento do universo e o peso da sabedoria adquirida.',
    'Roda':'Representa o ciclo eterno de nascimento, morte e renascimento; o movimento constante do destino e do tempo.',
    'Esfinge':'Simboliza o equilíbrio e a estabilidade em meio à mudança. Ela detém a espada da justiça, representando a lei espiritual que governa o destino.',
    'Os Quatro Seres.':'O Anjo (Aquário), a Águia (Escorpião), o Leão (Leão) e o Touro (Touro). Representam os quatro elementos e a estabilidade do mundo físico em meio ao caos.',
    'Símbolos Alquímicos':'No círculo interno, aparecem símbolos para Mercúrio, Enxofre, Sal e Água, ou seja, os componentes básicos da vida e da transformação.',
    'Apófis':' A serpente descendo na Roda da Fortuna simboliza a força involutiva, a queda na matéria ou os instintos que nos prendem aos ciclos terrenos.',
    'Hermanúbis':'Representa a inteligência, a sabedoria e a necessidade de equilíbrio entre forças opostas durante os ciclos de mudança da vida. O intermediário entre o consciente e o inconsciente, ou entre a vida e a morte. Indica ascensão, evolução espiritual e a inteligência necessária para navegar as mudanças súbitas.',
    'Mulher':'Representa o Self consciente e a inteligência emocional. É a psique superior que atua através da paciência e da diplomacia, e não da força bruta.',
    'Leão':'Simboliza o Id, os impulsos instintivos, a raiva, a libido e as paixões cruas. É a nossa natureza animal que precisa de integração, não de repressão.',
    'Coroa de Flores':'Harmonia entre o humano e o divino, vitória espiritual, celebração da vida e a conexão com a natureza. Diferente da coroa de metal (que representa autoridade mundana/rígida), a coroa de flores sugere uma liderança ou vitória baseada na compaixão, intuição e inteligência emocional.',
    'Postura Invertida':'Representa a inversão de valores e a mudança de perspectiva. Na saúde mental, simboliza olhar para um problema de um ângulo completamente novo, rompendo padrões cognitivos habituais.',
    'Árvore':'Simboliza a contínua renovação e o processo de crescimento. Funciona como ponte entre o divino (céu) e o terreno.',
    'Auréola':'A luz ao redor da cabeça indica iluminação, insight e clareza mental. Sugere que a compreensão profunda surge quando cessamos a luta externa e nos voltamos para a introspecção.',
    'Pernas Cruzadas':'A perna cruzada forma o número quatro, associado à estabilidade e ao mundo material. No Arcano O Pendurado, indica que o mundo físico está em suspensão, priorizando o trabalho interno sobre a ação externa.',
    'Braços formando um Triângulo':'Os braços dobrados atrás das costas formam um triângulo invertido, símbolo da água e do receptivo. Representa a submissão consciente e a abertura para receber sabedoria sem resistência.',
    'Esqueleto':'Representa a estrutura que permanece após o que é efêmero desaparecer.',
    'Armadura Negra':'Simboliza a invencibilidade e a inevitabilidade da mudança, que não pode ser detida por defesas externas.',
    'Cavalo Branco':'O cavalo branco simboliza a pureza do movimento e a força vital que conduz a transformação. Sua cor indica que a mudança, embora difícil, é um processo de limpeza e clareza.',
    'Água':'Representa o subconsciente, as emoções e o fluxo da intuição. É o elemento da cura e da limpeza emocional.',
    'Ânfora':'Recipiente da energia vital; simboliza a capacidade de conter, dosar e distribuir nossas emoções com equilíbrio.',
    'Anjo':'Representa o "Eu Superior" ou a superconsciência. É o guia que traz clareza espiritual e proteção.',
    'Asas':'Simbolizam a capacidade de elevação mental e espiritual; o poder de transcender limitações materiais.',
    'Asas de Morcego':'Simbolizam o pensamento obscurecido, o apego ao abismo da mente e a incapacidade de "voar" para a luz.',
    'Asas Vermelhas':'Representam a paixão espiritualizada e a energia vital ativa que impulsiona a alma.',
    'Bandeira Cristã':'A cruz vermelha em fundo branco simboliza a vitória do espírito sobre a morte e o despertar da consciência.',
    'Bastões':'Representam a vontade, a criatividade, o impulso vital e a autoridade mágica.',
    'Bode':'Representa os instintos primordiais, a fertilidade descontrolada e a sombra que precisa ser integrada.',
    'Uva':'Simboliza a abundância, os prazeres sensoriais e, em excesso, a embriaguez ou o vício material.',
    'Cálice':'Representa o elemento Água: receptáculo dos sentimentos, do amor, da intuição e da receptividade da alma.',
    'Caminho':'A jornada da vida; representa o processo de evolução e a distância a ser percorrida até a iluminação.',
    'Chifres':'Simbolizam o poder animal, a força bruta.',
    'Bastões (Dois)':'Simbolizam o domínio total sobre as polaridades, positiva e negativa e a manifestação completa',
    'Coroa':'Representa o topo da cabeça (Chacra Coronário), a autoridade, a conquista e o controle do ego ou do espírito.',
    'Correntes':'Simbolizam o aprisionamento psicológico, vícios, dependências e a ilusão de estar preso por forças externas.',
    'Criança':'O arquétipo da pureza, da vulnerabilidade renovada, da alegria genuína e do novo começo sem preconceitos.',
    'Diabo':'Personificação das sombras internas, medos, obsessões e o foco exclusivo no plano material.',
    'Estandarte Vermelho':'Símbolo de vitalidade vibrante e da vitória solar sobre a escuridão; a celebração da vida.',
    'Estrela':'Guia de esperança e renovação; representa a luz interna que brilha após os momentos de crise.',
    'Fita Vermelha':'Representa o "fio" da vida, a paixão ou a conexão entre o espírito e a ação física.',
    'Flores (Íris)':'Mensageiras de harmonia e paz; simbolizam a moderação e a comunicação entre o céu e a terra.',
    'Fogo':'Energia de transformação, destruição necessária e faísca divina da inspiração e do desejo.',
    'Girassol':'A alma voltada para a luz; representa felicidade, vitalidade, crescimento e o sucesso absoluto.',
    'Guirlanda de Louros':'Símbolo de conclusão bem-sucedida, triunfo, proteção e o ciclo eterno da vida que se fecha.',
    'Lago':'O reservatório do inconsciente; águas paradas que guardam mistérios, sonhos e medos profundos.',
    'Lagosta':'Representa os primeiros impulsos da consciência emergindo do subconsciente; o enfrentar de medos arcaicos.',
    'Lobo':'O instinto selvagem e o medo do desconhecido; a parte da natureza humana que ainda não foi domesticada.',
    'Lua':'O reino das ilusões, dos sonhos e da intuição; reflete a luz solar de forma indireta e misteriosa.',
    'Nuvens Cincentas':'Simbolizam confusão mental, turbulência emocional ou o véu que encobre a verdade temporariamente.',
    'Pássaro (Íbis)':'Símbolo da sabedoria sagrada e da mente que se eleva para observar a realidade de um ponto de vista superior.',
    'Pentagrama Invertido':'Simboliza a matéria dominando o espírito; a inversão dos valores éticos e o foco no ego.',
    'Raio':'Intervenção súbita, quebra de paradigmas, "insight" violento e a destruição de falsas certezas.',
    'Reflexo':'A dualidade entre o que é real e o que é percebido; a projeção das nossas sombras no mundo exterior.',
    'Seios Fartos':'Simbolizam nutrição, fertilidade, maternidade e a abundância da natureza que sustenta a vida.',
    'Torre':'As construções do ego; estruturas rígidas que precisam cair para permitir o crescimento da alma.',
    'Triângulo':'Representa a tríade (corpo, mente e espírito); o fogo da aspiração espiritual.',
    'Trombeta':'O chamado para o despertar; o som que ativa a consciência e convoca para a renovação.',
    'Trono':'Símbolo de estabilidade, autoridade e o lugar onde a consciência se assenta para governar a vida.',
    'Túmulo':'Representa o passado, a estagnação ou o estado de "morte em vida" de onde a alma deve ressurgir.',
    'Yod':'Gota de luz ou letra hebraica; simboliza a centelha divina e a graça que desce para nutrir o mundo físico.',
};
const listaSimbolos = document.getElementById('simbolos');
Object.entries(dicionarioSimbolos)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .forEach(([chave, valor]) => {
        const itemLista = document.createElement('li');
        itemLista.innerHTML = `
            <span class="chave">${chave}:</span> 
            <span class="valor">${valor}</span>
        `;
        listaSimbolos.appendChild(itemLista);
    });